"""added desc column in courses

Revision ID: 394d1bd1867b
Revises: b2ab087bcc33
Create Date: 2024-05-24 17:44:40.041856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '394d1bd1867b'
down_revision = 'b2ab087bcc33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
