"""added tags model

Revision ID: b2ab087bcc33
Revises: 5efa91df3c5f
Create Date: 2024-05-24 16:13:43.867489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2ab087bcc33'
down_revision = '5efa91df3c5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('tags',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('tags',
               existing_type=sa.VARCHAR(),
               nullable=True)

    op.drop_table('tag')
    # ### end Alembic commands ###
